type: "simulstream.server.speech_processors.qwenomni_doa.Qwen3OmniDOA"
text_history:
  type: "simulstream.server.speech_processors.base_streamatt.PunctuationTextHistory"
audio_history_max_duration: 60  # Maximum length for the audio buffer, in seconds
text_history_max_len: 128
speech_chunk_size: 1  # seconds
attn_layer: __LAYER__
attn_head: null  # Optional specific head; null means average over heads
average_attn_over_layers: True
cutoff_frame_num: __FRAME__
detokenizer_type: "hf"
hf_model_name: "Qwen/Qwen3-Omni-30B-A3B-Instruct"
word_level_postprocess: True  # Disable if character-level language
max_new_tokens: 32
bow_prefix: " "
prompt: "You are a professional {src_lang}-to-{tgt_lang} translator. Your goal is to accurately \
convey the meaning and nuances of the original {src_lang} speech while adhering to {tgt_lang} \
grammar, vocabulary, and cultural sensitivities. Use precise terminology and a tone appropriate \
for academic or instructional materials. Produce only the {tgt_lang} translation, without any \
additional explanations or commentary. Please translate the provided {src_lang} speech into \
{tgt_lang}:"