type: "simulstream.server.speech_processors.ultravox_doa.UltravoxDOA"
text_history:
  type: "simulstream.server.speech_processors.base_streamatt.PunctuationTextHistory"
audio_history_max_duration: 120  # Maximum length for the audio buffer, in seconds
text_history_max_len: 128
speech_chunk_size: 1  # seconds
attn_layer: __LAYER__
attn_head: null  # Optional specific head; null means average over heads
average_attn_over_layers: True
cutoff_frame_num: __FRAME__
detokenizer_type: "hf"
hf_model_name: "fixie-ai/ultravox-v0_6-llama-3_1-8b"e
word_level_postprocess: True  # Disable if character-level language
max_new_tokens: 32